# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeBOAEigen <- function(awake, eta, experts, weights, y, predictions, wc, w0c, Rc, Regc, Bc, Vc, loss_name, loss_tau, loss_gradient, quiet) {
    invisible(.Call('_opera_computeBOAEigen', PACKAGE = 'opera', awake, eta, experts, weights, y, predictions, wc, w0c, Rc, Regc, Bc, Vc, loss_name, loss_tau, loss_gradient, quiet))
}

computeEWAEigen <- function(awake, experts, weights, y, predictions, w0c, eta, cumulativeLoss, loss_name, loss_tau, loss_gradient, quiet) {
    .Call('_opera_computeEWAEigen', PACKAGE = 'opera', awake, experts, weights, y, predictions, w0c, eta, cumulativeLoss, loss_name, loss_tau, loss_gradient, quiet)
}

computeMLPolCPP <- function(awake, eta, experts, weights, y, predictions, R, w, B, loss_name, loss_tau, loss_gradient, quiet) {
    .Call('_opera_computeMLPolCPP', PACKAGE = 'opera', awake, eta, experts, weights, y, predictions, R, w, B, loss_name, loss_tau, loss_gradient, quiet)
}

computeMLPolEigen <- function(awake, eta, experts, weights, y, predictions, R, w, B, loss_name, loss_tau, loss_gradient, quiet) {
    .Call('_opera_computeMLPolEigen', PACKAGE = 'opera', awake, eta, experts, weights, y, predictions, R, w, B, loss_name, loss_tau, loss_gradient, quiet)
}

computeMLPolEigenSimpleLoss <- function(awake, eta, experts, weights, y, predictions, Rc, wc, B, loss_name, loss_tau, loss_gradient, quiet) {
    .Call('_opera_computeMLPolEigenSimpleLoss', PACKAGE = 'opera', awake, eta, experts, weights, y, predictions, Rc, wc, B, loss_name, loss_tau, loss_gradient, quiet)
}

computeMLProdEigen <- function(awake, eta, experts, weights, y, predictions, R, L, maxloss, loss_name, loss_tau, loss_gradient, quiet) {
    invisible(.Call('_opera_computeMLProdEigen', PACKAGE = 'opera', awake, eta, experts, weights, y, predictions, R, L, maxloss, loss_name, loss_tau, loss_gradient, quiet))
}

RidgeCalibStep1 <- function(tp1, dbestlambda, experts, weights, wlambda, w0, bt, gridlambda, y, lambda, cumulativeloss, prediction) {
    .Call('_opera_RidgeCalibStep1', PACKAGE = 'opera', tp1, dbestlambda, experts, weights, wlambda, w0, bt, gridlambda, y, lambda, cumulativeloss, prediction)
}

computeRidgeCPP <- function(experts, w, At, bt, y, quiet) {
    .Call('_opera_computeRidgeCPP', PACKAGE = 'opera', experts, w, At, bt, y, quiet)
}

computeEWACalib <- function(tp1, dbesteta, awake, experts, weights, weta, w0, grideta, y, eta, cumulativeloss, prediction, loss_name, loss_tau, loss_gradient) {
    .Call('_opera_computeEWACalib', PACKAGE = 'opera', tp1, dbesteta, awake, experts, weights, weta, w0, grideta, y, eta, cumulativeloss, prediction, loss_name, loss_tau, loss_gradient)
}

count_in <- function(x, y) {
    .Call('_opera_count_in', PACKAGE = 'opera', x, y)
}

init_progress_cpp <- function(T) {
    .Call('_opera_init_progress_cpp', PACKAGE = 'opera', T)
}

update_progress_cpp <- function(t, steps) {
    invisible(.Call('_opera_update_progress_cpp', PACKAGE = 'opera', t, steps))
}

end_progress_cpp <- function() {
    invisible(.Call('_opera_end_progress_cpp', PACKAGE = 'opera'))
}

