# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeBOAEigen <- function(awake, eta, experts, weights, y, predictions, wc, w0c, Rc, Regc, Bc, Vc, loss_name, loss_tau, loss_gradient) {
    invisible(.Call('_opera_computeBOAEigen', PACKAGE = 'opera', awake, eta, experts, weights, y, predictions, wc, w0c, Rc, Regc, Bc, Vc, loss_name, loss_tau, loss_gradient))
}

computeEWAEigen <- function(awake, experts, weights, y, predictions, w0c, eta, cumulativeLoss, loss_name, loss_tau, loss_gradient) {
    .Call('_opera_computeEWAEigen', PACKAGE = 'opera', awake, experts, weights, y, predictions, w0c, eta, cumulativeLoss, loss_name, loss_tau, loss_gradient)
}

computeMLPolCPP <- function(awake, eta, experts, weights, y, predictions, R, w, B, loss_name, loss_tau, loss_gradient) {
    .Call('_opera_computeMLPolCPP', PACKAGE = 'opera', awake, eta, experts, weights, y, predictions, R, w, B, loss_name, loss_tau, loss_gradient)
}

computeMLPolEigen <- function(awake, eta, experts, weights, y, predictions, R, w, B, loss_name, loss_tau, loss_gradient) {
    .Call('_opera_computeMLPolEigen', PACKAGE = 'opera', awake, eta, experts, weights, y, predictions, R, w, B, loss_name, loss_tau, loss_gradient)
}

computeMLPolEigenSimpleLoss <- function(awake, eta, experts, weights, y, predictions, Rc, wc, B, loss_name, loss_tau, loss_gradient) {
    .Call('_opera_computeMLPolEigenSimpleLoss', PACKAGE = 'opera', awake, eta, experts, weights, y, predictions, Rc, wc, B, loss_name, loss_tau, loss_gradient)
}

computeMLProdEigen <- function(awake, eta, experts, weights, y, predictions, R, L, maxloss, loss_name, loss_tau, loss_gradient) {
    invisible(.Call('_opera_computeMLProdEigen', PACKAGE = 'opera', awake, eta, experts, weights, y, predictions, R, L, maxloss, loss_name, loss_tau, loss_gradient))
}

RidgeCalibStep1 <- function(tp1, dbestlambda, experts, weights, wlambda, w0, At, bt, gridlambda, predlambda, y, lambda, cumulativeloss, prediction) {
    .Call('_opera_RidgeCalibStep1', PACKAGE = 'opera', tp1, dbestlambda, experts, weights, wlambda, w0, At, bt, gridlambda, predlambda, y, lambda, cumulativeloss, prediction)
}

RidgeCalibStep2 <- function(wlambda, w0, At, bt, gridlambda) {
    invisible(.Call('_opera_RidgeCalibStep2', PACKAGE = 'opera', wlambda, w0, At, bt, gridlambda))
}

computeRidgeCPP <- function(experts, w, At, bt, y) {
    .Call('_opera_computeRidgeCPP', PACKAGE = 'opera', experts, w, At, bt, y)
}

computeEWACalib <- function(tp1, dbesteta, awake, experts, weights, weta, w0, grideta, y, eta, cumulativeloss, prediction, loss_name, loss_tau, loss_gradient) {
    .Call('_opera_computeEWACalib', PACKAGE = 'opera', tp1, dbesteta, awake, experts, weights, weta, w0, grideta, y, eta, cumulativeloss, prediction, loss_name, loss_tau, loss_gradient)
}

